FROM centos:7.9.2009
RUN yum install -y httpd \
zip \
unzip
ADD https://www.free-css.com/assets/files/free-css-templates/download/page279/farm-stead.zip/var/www/html/=
WORKDIR /var/www/html
RUN unzip farm-stead.zip
RUN cp -rvf farm-stead-template/* .
RUN rm -rf farm-stead.zip
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
EXPOSE 80